build: Fix golangci-lint installation
`make` currently fails with:
```
go test ./...
?   	github.com/code-ready/machine-driver-libvirt/cmd/machine-driver-libvirt	[no test files]
ok  	github.com/code-ready/machine-driver-libvirt/pkg/libvirt	0.028s
go: go.mod file not found in current directory or any parent directory.
	'go get' is no longer supported outside a module.
	To build and install a command, use 'go install' with a version,
	like 'go install example.com/cmd@latest'
	For more information, see https://golang.org/doc/go-get-install-deprecation
	or run 'go help get' or 'go help install'.
make: *** [Makefile:55: golangci-lint] Error 1
Error: error building at STEP "RUN make validate": error while running runtime: exit status 2
```

This commit uses the same approach as crc main branch to download/build
golangci-lint. This should fix this error.